### ISSUE TITLE
Custom data mask usage 

### ISSUE THREAD

**Issue by jijiangli-swu-worker** [yanivw12/gs2mesh#14]
Great work! I try your code on cudom datasets such as nerf castle, amazing performance! But I have some trouble to specify the masks during training. As I see the readme you said that there are some ways to perform automasking the scene, how could I specify the masks I have already prepare for each images such as what if I provide a data with rgba? As the the auto mask are not what I am expecting for.

**Comment by yanivw12** [comment]
If you use your own masks, you should save them after the stereo model finishes running in the "output" folder. The output folder should contain folders named 000, 001 etc, which correspond to the order of the input views. Each folder looks like this:
![image](https://github.com/user-attachments/assets/326d761d-82eb-441d-8029-f2775ef21b59)
For you to use your own masks, save the masks as a .npy file as seen in the example above, and when running the code use the flag --TSDF_use_mask.

By the way, sometimes GroundingDino+SAM2 fails for complex objects, but I found that it can help if you choose to segment the background (for example the table) and then invert the mask using --TSDF_invert_mask, and let the TSDF depth truncation do the rest. If the mask is still not what you were expecting, you can always use the interactive Jupyter notebook custom_data.py, where you can interactively click and fine-tune the area you want to mask.

**Comment by jijiangli-swu-worker** [comment]
Thank for your help! I modify it like you do in mobiletrick dataset.
