### ISSUE TITLE
Poor results of Truck dataset

### ISSUE THREAD

**Issue by ThePassedWind** [yanivw12/gs2mesh#16]
Dear author, I notice you discussed the bad results of 2DGS/GOF on TNT datasets.
https://github.com/hbb1/2d-gaussian-splatting/issues/111
https://github.com/autonomousvision/gaussian-opacity-fields/issues/70

I face the same problem at present and want to ask if you have solved this problem?
What is the reason?
Looking forward to your reply!

Thanks~

**Comment by ThePassedWind** [comment]
![image](https://github.com/user-attachments/assets/34b21899-4fec-446b-947f-c15529996ecb)

**Comment by yanivw12** [comment]
I solved it by downloading the correct SfM files directly from the TNT website and then running the preprocessing code. You can follow the instructions in this repository for preprocessing the TNT dataset, just make sure you download the correct files directly from the TNT website and it should work fine.

**Comment by ThePassedWind** [comment]
> I solved it by downloading the correct SfM files directly from the TNT website and then running the preprocessing code. You can follow the instructions in this repository for preprocessing the TNT dataset, just make sure you download the correct files directly from the TNT website and it should work fine.

Ohh, "Correct Sfm files" are only {scene}_COLMAP_SfM.log files?

**Comment by yanivw12** [comment]
> > I solved it by downloading the correct SfM files directly from the TNT website and then running the preprocessing code. You can follow the instructions in this repository for preprocessing the TNT dataset, just make sure you download the correct files directly from the TNT website and it should work fine.
> 
> Ohh, "Correct Sfm files" are only {scene}_COLMAP_SfM.log files?

Yes, exactly.

**Comment by ThePassedWind** [comment]
Thanks for your help~
