### ISSUE TITLE
I don't know where segment-anything-2 was applied

### ISSUE THREAD

**Issue by anshanYCL** [yanivw12/gs2mesh#6]
have a nice day!!!
I don't know where segment-anything-2 was applied
Even without installing segment-anything-2, I can still obtain a mesh result from custom data
Doesn't custom data require segment-anything-2?

**Comment by anshanYCL** [comment]
Additionally, I noticed that the input image has not been fully colmapped. For example, when I input 100 images of a Lego car, only 4 images are available for colmap? What is the reason for this?

**Comment by yanivw12** [comment]
> have a nice day!!! I don't know where segment-anything-2 was applied Even without installing segment-anything-2, I can still obtain a mesh result from custom data Doesn't custom data require segment-anything-2?

SAM2 was applied only in the interactive notebook (custom_data.ipynb), as it requires a prompt of clicking the object in the first frame. You don't have to use SAM2 for custom data, it should work without it as well (usually the TSDF_max_depth_baselines parameter truncates the depth image and removes most of the background). I might add in the future the option to segment an object using a text prompt with SAM2.

> Additionally, I noticed that the input image has not been fully colmapped. For example, when I input 100 images of a Lego car, only 4 images are available for colmap? What is the reason for this?

Can you give more details? Was it a custom dataset or the MobileBrick dataset? Are you using the latest version of the repository? What was the resolution of the images?

**Comment by anshanYCL** [comment]
> > have a nice day!!! I don't know where segment-anything-2 was applied Even without installing segment-anything-2, I can still obtain a mesh result from custom data Doesn't custom data require segment-anything-2?
> 
> SAM2 was applied only in the interactive notebook (custom_data.ipynb), as it requires a prompt of clicking the object in the first frame. You don't have to use SAM2 for custom data, it should work without it as well (usually the TSDF_max_depth_baselines parameter truncates the depth image and removes most of the background). I might add in the future the option to segment an object using a text prompt with SAM2.
> 
> > Additionally, I noticed that the input image has not been fully colmapped. For example, when I input 100 images of a Lego car, only 4 images are available for colmap? What is the reason for this?
> 
> Can you give more details? Was it a custom dataset or the MobileBrick dataset? Are you using the latest version of the repository? What was the resolution of the images?

Thank you for your reply
I used the traditional NERF data Lego car as a custom dataset for processing, with a total of 100 images. Using other customized data, I took 195 pictures of chairs, and the final number of completed colmaps was 190, with some missing parts. Although it does not affect usage.
The resolution of Lego data is 800 * 800.
The generated result file is particularly large. Will we consider some model compression in the future?
Also, if I am not satisfied with the modeling results, what parameters can I optimize through? Do you have any relevant suggestions?

**Comment by anshanYCL** [comment]
> > have a nice day!!! I don't know where segment-anything-2 was applied Even without installing segment-anything-2, I can still obtain a mesh result from custom data Doesn't custom data require segment-anything-2?
> 
> SAM2 was applied only in the interactive notebook (custom_data.ipynb), as it requires a prompt of clicking the object in the first frame. You don't have to use SAM2 for custom data, it should work without it as well (usually the TSDF_max_depth_baselines parameter truncates the depth image and removes most of the background). I might add in the future the option to segment an object using a text prompt with SAM2.
> 
> > Additionally, I noticed that the input image has not been fully colmapped. For example, when I input 100 images of a Lego car, only 4 images are available for colmap? What is the reason for this?
> 
> Can you give more details? Was it a custom dataset or the MobileBrick dataset? Are you using the latest version of the repository? What was the resolution of the images?

Sorry, I encountered another issue while running custom_data.ipynb. I am unable to access huggingface. co, but I have downloaded sam_2hiera_barge.pt locally. Can you tell me where sam_2hiera_barge.pt should be placed to ensure successful running of sam2?

**Comment by anshanYCL** [comment]
thanks，i know。good job！

**Comment by yanivw12** [comment]
> have a nice day!!! I don't know where segment-anything-2 was applied Even without installing segment-anything-2, I can still obtain a mesh result from custom data Doesn't custom data require segment-anything-2?

Update: I just pushed an update with support for automatic masking with GroundingDINO, so you can run the script without the notebook and segment specific objects/remove background. See the main page README for more details.
